Repository OWASP/www-project-developer-guide, pull requests merged in 2023-06, with the labels that each got.

#42 Add daily housekeeping workflow
  .github/workflows/housekeeping.yaml
Labels: automation

#45 add alternative artwork
  assets/images/alt-owasp-dev-guide.png
Labels: artwork

#47 increase link-checker retries
  .github/workflows/ci.yaml
  .github/workflows/housekeeping.yaml
Labels: automation

#53 update pipeline actions for latest versions
  .github/workflows/ci.yaml
  .github/workflows/housekeeping.yaml
Labels: automation

#50 Update 02-system-hardening.md
  .wordlist.txt
  draft/09-secure-environment/02-system-hardening.md
Labels: content

#49 Update 01-open-source-software.md
  .wordlist.txt
  draft/08-open-source-software/01-open-source-software.md
Labels: content

#56 Add files via upload
  .lycheeignore
  assets/images/dg_logo.png
  assets/images/dg_logo_bbd.png
  assets/images/dg_logo_di.png
Labels: artwork
