Repository OWASP/www-project-developer-guide, pull requests merged in 2023-07, with the labels that each got.

#40 add section on Secure Development
  .github/workflows/ci.yaml
  .github/workflows/housekeeping.yaml
  .gitignore
  .wordlist.txt
  _data/draft.yaml
  contributing.md
  draft/00-toc.md
  draft/01-audience.md
  draft/02-background.md
  draft/03-introduction.md
  draft/04-foundations/00-toc.md
  draft/04-foundations/01-security-fundamentals.md
  draft/04-foundations/02-sdlc.md
  draft/04-foundations/02-secure-development.md
  draft/04-foundations/03-security-principles.md
  draft/04-foundations/04-crypto-principles.md
  draft/04-foundations/toc.md
  draft/05-security-requirements/00-toc.md
  draft/05-security-requirements/01-security-requirements.md
  draft/05-security-requirements/02-threat-modeling.md
  draft/05-security-requirements/03-risk-profile.md
  draft/05-security-requirements/toc.md
  draft/06-secure-design/00-toc.md
  draft/06-secure-design/01-secure-design.md
  draft/06-secure-design/02-secure-coding.md
  draft/06-secure-design/03-cryptographic-practices.md
  draft/06-secure-design/04-application-spoofing.md
  draft/06-secure-design/05-content-security-policy.md
  draft/06-secure-design/06-exception-error-handling.md
  draft/06-secure-design/07-file-management.md
  draft/06-secure-design/08-memory-management.md
  draft/06-secure-design/toc.md
  draft/07-container-security/00-toc.md
  draft/07-container-security/01-container-security.md
  draft/07-container-security/02-image-security.md
  draft/07-container-security/03-container-scanning.md
  draft/07-container-security/toc.md
  draft/08-open-source-software/00-toc.md
  draft/08-open-source-software/01-open-source-software.md
  draft/08-open-source-software/02-sca.md
  draft/08-open-source-software/03-tps.md
  draft/08-open-source-software/toc.md
  draft/09-secure-environment/00-toc.md
  draft/09-secure-environment/01-secure-environment.md
  draft/09-secure-environment/02-system-hardening.md
  draft/09-secure-environment/03-files.md
  draft/09-secure-environment/toc.md
  draft/10-security-testing-validation/00-toc.md
  draft/10-security-testing-validation/01-security-testing-validation.md
  draft/10-security-testing-validation/02-sast.md
  draft/10-security-testing-validation/03-dast.md
  draft/10-security-testing-validation/toc.md
  draft/assets/images/01x01-CIA_Triad.png
  draft/assets/images/02x01-Policies.png
  draft/assets/images/Input Validation.png
  draft/assets/images/KeyMgmt.png
  draft/assets/images/NIST-key-states-transitions.png
  draft/assets/images/sdlc_diag.png
  draft/toc.md
  security.md
Labels: content

#58 Update toc.md
  .wordlist.txt
  draft/00-toc.md
  draft/04-foundations/02-secure-development.md
  draft/toc.md
Labels: bug

#59 Automation: corrections to diagrams for pandoc
  .github/workflows/ci.yaml
  contributing.md
  draft/00-toc.md
  draft/04-foundations/02-secure-development.md
  draft/toc.md
Labels: automation

#60 add logo to index and read-me
  README.md
  index.md
Labels: enhancement

#61 add tab on contributing
  .gitignore
  .wordlist.txt
  draft/05-security-requirements/00-toc.md
  draft/06-secure-design/00-toc.md
  draft/07-container-security/00-toc.md
  draft/08-open-source-software/00-toc.md
  draft/09-secure-environment/00-toc.md
  draft/10-security-testing-validation/00-toc.md
  tab_contributing.md
Labels: enhancement

#65 Fix links
  .github/ISSUE_TEMPLATE/content.md
  .github/ISSUE_TEMPLATE/request.md
  _data/draft.yaml
  draft/04-foundations/01-security-fundamentals.md
Labels: content

#66 update link for ThreatSpec tool
  draft/05-security-requirements/02-threat-modeling.md
Labels: bug
