Repository OWASP/www-project-developer-guide, pull requests merged in 2024-08, with the labels that each got.

#249 update SamuraiWTF logos
  .lycheeignore
  assets/images/logos/samuraiwtf.png
  draft/09-training-education/04-samurai-wtf.md
  release/08-verification/01-guides/toc.md
  release/08-verification/toc.md
  release/toc.md
Labels: content

#251 Security principles
  draft/04-foundations/03-security-principles.md
Labels: content

#253 Update 03-security-principles.md
  .wordlist.txt
  draft/01-front.md
  draft/04-foundations/03-security-principles.md
Labels: content

#257 provide section on HTML
  .github/pull_request_template.md
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  .gitignore
  .wordlist.txt
  README.md
  assets/images/owasp-wayfinder.png
  assets/images/sdlc_diag.png
  draft/03-introduction.md
  draft/04-foundations/00-toc.md
  draft/04-foundations/01-security-fundamentals.md
  draft/04-foundations/02-secure-development.md
  draft/04-foundations/03-security-principles.md
  draft/04-foundations/toc.md
  draft/06-design/01-threat-modeling/01-threat-modeling.md
  draft/06-design/02-web-app-checklist/02-frameworks-libraries.md
  draft/06-design/02-web-app-checklist/05-validate-inputs.md
  draft/10-culture-process/03-samm.md
  index.md
  info.md
  release-process.md
Labels: content

#260 add pre-release candidate to release workflow
  .github/workflows/release.yaml
  README.md
  contributing.md
  draft/04-foundations/01-security-fundamentals.md
  draft/10-culture-process/03-samm.md
  draft/13-security-gap-analysis/01-guides/01-samm.md
Labels: automation

#262 Update index.md
  index.md
Labels: content

#264 promotion to lab project
  README.md
  info.md
Labels: documentation

#261 prepare to add page for OpenCRE
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  .gitignore
  .wordlist.txt
  _data/draft.yaml
  _data/release.yaml
  assets/css/styles.scss
  assets/images/owasp-wayfinder.png
  draft/01-front.md
  draft/02-toc.md
  draft/03-introduction.md
  draft/04-foundations/01-security-fundamentals.md
  draft/04-foundations/02-secure-development.md
  draft/05-requirements/00-toc.md
  draft/05-requirements/03-opencre.md
  draft/05-requirements/07-skf.md
  draft/05-requirements/toc.md
  draft/10-culture-process/03-samm.md
  draft/10-culture-process/04-asvs.md
  draft/10-culture-process/05-mas.md
  draft/12-metrics/00-toc.md
  draft/12-metrics/toc.md
  draft/13-security-gap-analysis/01-guides/01-samm.md
  draft/toc.md
  info.md
  release/02-toc.md
  release/05-requirements/00-toc.md
  release/05-requirements/03-opencre.md
  release/05-requirements/07-skf.md
  release/05-requirements/toc.md
  release/toc.md
  tab_historical.md
Labels: content
