Repository OWASP/www-project-developer-guide, pull requests merged in 2025-01, with the labels that each got.

#319 Use EN-US consistently
  .spellcheck-en.yaml
  .wordlist-en.txt
  README.md
  contributing.md
  draft/04-foundations/02-secure-development.md
  draft/04-foundations/03-security-principles.md
  draft/04-foundations/05-top-ten.md
  draft/05-requirements/03-opencre.md
  draft/06-design/00-toc.md
  draft/06-design/01-threat-modeling/01-threat-modeling.md
  draft/06-design/01-threat-modeling/04-cornucopia.md
  draft/06-design/01-threat-modeling/06-toolkit.md
  draft/06-design/02-web-app-checklist/00-toc.md
  draft/06-design/02-web-app-checklist/02-frameworks-libraries.md
  draft/06-design/02-web-app-checklist/toc.md
  draft/06-design/toc.md
  draft/07-implementation/00-toc.md
  draft/07-implementation/01-documentation/03-cheatsheets.md
  draft/07-implementation/02-dependencies/02-dependency-track.md
  draft/07-implementation/03-secure-libraries/00-toc.md
  draft/07-implementation/03-secure-libraries/toc.md
  draft/07-implementation/04-maswe.md
  draft/07-implementation/toc.md
  draft/08-verification/02-tools/03-owtf.md
  draft/09-training-education/00-toc.md
  draft/09-training-education/01-vulnerable-apps/02-webgoat.md
  draft/09-training-education/09-snakes-ladders.md
  draft/09-training-education/toc.md
  draft/10-culture-process/01-security-culture.md
  draft/10-culture-process/02-security-champions/01-security-champions-program.md
  draft/10-culture-process/04-asvs.md
  draft/14-appendices/01-implementation-dos-donts/01-container-security.md
  draft/14-appendices/01-implementation-dos-donts/02-secure-coding.md
  draft/14-appendices/01-implementation-dos-donts/03-cryptographic-practices.md
  draft/14-appendices/02-verification-dos-donts/03-open-source-software.md
Labels: enhancement, translation

#320 PT-BR spellcheck calls pyspelling direct
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  .spellcheck-pt-br.yaml
Labels: bug, automation, translation

#326 Translate sidebar to Brazilian Portuguese
  _data/release-pt-br.yaml
Labels: content, translation

#274 Translate chapter 04: sections 01, 05 and TOC to Brazilian Portuguese
  release-pt-br/04-foundations/00-toc.md
  release-pt-br/04-foundations/01-security-fundamentals.md
  release-pt-br/04-foundations/05-top-ten.md
  release-pt-br/04-foundations/toc.md
Labels: content, translation

#332 Translate 03-introduction to Brazilian Portuguese
  release-pt-br/03-introduction.md
Labels: content, translation
